#!/usr/bin/env -S deno run --allow-all
/**
 * tool/gen_schema.ts — Schema fence generator for the TheLIST backend.
 *
 * Reads all SQL files in supabase/migrations/ in lexicographic order,
 * concatenates the CREATE TABLE / CREATE INDEX / ALTER TABLE statements,
 * and writes them into the fenced <!-- SCHEMA --> region in
 * docs/architecture/schema.md.
 *
 * Usage:
 *   deno run --allow-all tool/gen_schema.ts          # update the fence
 *   deno run --allow-all tool/gen_schema.ts --check  # verify fence is current
 *
 * Exit 0 on success; exit 1 if --check and fence is stale.
 */

import { walk } from "https://deno.land/std@0.224.0/fs/walk.ts";
import { join } from "https://deno.land/std@0.224.0/path/mod.ts";

const ROOT = new URL("../", import.meta.url).pathname;
const MIGRATIONS_DIR = join(ROOT, "supabase/migrations");
const SCHEMA_DOC = join(ROOT, "docs/architecture/schema.md");
const CHECK = Deno.args.includes("--check");

const FENCE_OPEN = "<!-- SCHEMA -->";
const FENCE_CLOSE = "<!-- /SCHEMA -->";

// Collect migration files in order
const migrationFiles: string[] = [];
try {
  for await (const entry of walk(MIGRATIONS_DIR, {
    exts: [".sql"],
    includeDirs: false,
  })) {
    migrationFiles.push(entry.path);
  }
} catch {
  // No migrations yet
}
migrationFiles.sort();

const schemaLines: string[] = [
  "<!-- This block is generated by tool/gen_schema.ts. Do not edit by hand. -->",
  "```sql",
];

for (const file of migrationFiles) {
  const text = await Deno.readTextFile(file);
  // Extract DDL statements (CREATE, ALTER, CREATE INDEX, DROP)
  const ddlLines = text
    .split("\n")
    .filter(
      (line) =>
        /^\s*(?:CREATE|ALTER|DROP|COMMENT ON)/i.test(line) ||
        /^\s*(?:[A-Z_]+\s+\w)/i.test(line) ||
        line.trim().startsWith("--") ||
        line.trim().startsWith(")") ||
        line.trim() === ""
    );
  schemaLines.push(`-- Migration: ${file.split(/[/\\]/).pop()}`);
  schemaLines.push(...ddlLines);
  schemaLines.push("");
}
schemaLines.push("```");

const generated = schemaLines.join("\n");

// Read current schema doc
let docText: string;
try {
  docText = await Deno.readTextFile(SCHEMA_DOC);
} catch {
  console.error(`✗ gen_schema: ${SCHEMA_DOC} not found`);
  Deno.exit(1);
}

const openIdx = docText.indexOf(FENCE_OPEN);
const closeIdx = docText.indexOf(FENCE_CLOSE);

if (openIdx === -1 || closeIdx === -1) {
  console.error(
    `✗ gen_schema: fence markers ${FENCE_OPEN} / ${FENCE_CLOSE} not found in schema.md`
  );
  Deno.exit(1);
}

const before = docText.slice(0, openIdx + FENCE_OPEN.length);
const after = docText.slice(closeIdx);
const newDoc = `${before}\n${generated}\n${after}`;

if (CHECK) {
  if (newDoc === docText) {
    console.log("✓ schema-fresh: schema fence is up to date");
    Deno.exit(0);
  } else {
    console.error(
      "✗ schema-fresh: schema fence is stale. Run `make gen` to regenerate."
    );
    Deno.exit(1);
  }
}

await Deno.writeTextFile(SCHEMA_DOC, newDoc);
console.log("✓ gen_schema: schema fence updated in docs/architecture/schema.md");
