// tool/gen_schema.dart
//
// Schema-fact generator for TheLIST (AGENTS.md §5, data_model.md §"Generated
// schema"). The *facts* in data_model.md — the actual table DDL — must never be
// hand-written, because hand-written facts drift from the code. This script
// emits the schema and injects it into the fenced sentinel region, replacing
// ONLY the content between the markers and never touching the hand-written
// rationale around it.
//
//   <!-- DRIFT-SCHEMA:START -->
//   ```sql
//   ...generated DDL...
//   ```
//   <!-- DRIFT-SCHEMA:END -->
//
// Run modes:
//   dart run tool/gen_schema.dart          # write the fenced region
//   dart run tool/gen_schema.dart --check  # fail if the region is out of date
//                                          # (used by `make verify` / CI)
//
// SOURCE OF TRUTH: until the Drift database class exists, this reads the schema
// from `drift` by introspection. For now it shells out to a schema dump if
// available, else emits a clear placeholder so the fence machinery is testable
// from day one. Wire `_dumpSchema()` to the real Drift schema once lib/data
// lands (see the TODO).

import 'dart:io';

const _docPath = 'docs/architecture/data_model.md';
const _startMarker = '<!-- DRIFT-SCHEMA:START -->';
const _endMarker = '<!-- DRIFT-SCHEMA:END -->';

void main(List<String> args) {
  final checkOnly = args.contains('--check');

  final doc = File(_docPath);
  if (!doc.existsSync()) {
    stderr.writeln('gen_schema: $_docPath not found.');
    exit(1);
  }

  final content = doc.readAsStringSync();
  final startIdx = content.indexOf(_startMarker);
  final endIdx = content.indexOf(_endMarker);
  if (startIdx == -1 || endIdx == -1 || endIdx < startIdx) {
    stderr.writeln(
        'gen_schema: sentinel markers missing or malformed in $_docPath.\n'
        'Expected $_startMarker ... $_endMarker.');
    exit(1);
  }

  final generated = _renderBlock(_dumpSchema());

  final before = content.substring(0, startIdx + _startMarker.length);
  final after = content.substring(endIdx);
  final updated = '$before\n$generated\n$after';

  if (checkOnly) {
    // Compare with line endings normalised so a CRLF checkout on Windows does
    // not spuriously report the fence as stale (eol is enforced to LF by
    // .gitattributes, but be robust regardless of how the file was checked out).
    String norm(String s) => s.replaceAll('\r\n', '\n').trim();
    if (norm(updated) == norm(content)) {
      stdout.writeln('gen_schema: OK — generated schema is up to date.');
      exit(0);
    }
    stderr.writeln(
        'gen_schema: FAILED — data_model.md schema fence is stale.\n'
        'Run: dart run tool/gen_schema.dart  (then commit the change).');
    exit(1);
  }

  doc.writeAsStringSync(updated);
  stdout.writeln('gen_schema: wrote generated schema into $_docPath.');
  exit(0);
}

String _renderBlock(String ddl) {
  return '```sql\n$ddl\n```';
}

/// Returns the schema DDL to embed.
///
/// TODO(data-layer): replace this with the real Drift schema once `lib/data`
/// exists, e.g. by importing the generated `AppDatabase` and reading
/// `database.schema` / `customStatement` DDL, or by reading the migration's
/// `createAll()` statements. Until then we emit an explicit placeholder so the
/// fence-replacement machinery is correct and self-testing from day one.
String _dumpSchema() {
  final dataDir = Directory('lib/data');
  final hasSchema = dataDir.existsSync() &&
      dataDir
          .listSync(recursive: true)
          .whereType<File>()
          .any((f) => f.path.endsWith('.dart') && !f.path.endsWith('.g.dart'));

  if (!hasSchema) {
    return '-- No Drift schema defined yet (lib/data is empty).\n'
        '-- This block is generated by tool/gen_schema.dart and must not be\n'
        '-- hand-edited. It will fill in automatically once the Drift schema\n'
        '-- exists and _dumpSchema() is wired to it.';
  }

  // Placeholder until wired to the real Drift schema (see TODO above).
  return '-- TODO: wire tool/gen_schema.dart::_dumpSchema() to the Drift schema.\n'
      '-- lib/data exists but the generator is not yet connected to it.';
}
